plugins:
  - vyper
  - foundry
  - etherscan
foundry:
  host: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry